---
- hosts: all
  become: yes
  tasks:
  - name: install webserver
    apt:
      name: apache2
      state: present 
  - name: I want to start webserver
    service:
      name: apache2
      state: started